name: Deploy to Server

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file locally
        run: |
          cat > .env << EOF
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t sch_board_crawler:latest . --load
          docker save sch_board_crawler:latest > sch_board_crawler-all.jar

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "sch_board_crawler-all.jar,docker-compose.yml,.env"
          target: "/home/${{ secrets.SERVER_USER }}sch_board_crawler/"

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/sch_board_crawler

            # Docker 이미지 로드
            docker load < sch_board_crawler-all.jar

            # 기존 컨테이너 중지 및 제거
            docker compose down || true

            # 새 컨테이너 시작
            docker compose up -d

            # 사용하지 않는 이미지 정리
            docker image prune -f

            # 상태 확인
            sleep 10
            docker compose ps
